default_language_version:
    python: python3.12

default_install_hook_types: [pre-commit, post-checkout, post-merge]

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: "cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b" # frozen: v5.0.0
      hooks:
          - id: check-added-large-files
            args: ["--maxkb=5000"]
          - id: check-ast
          - id: check-builtin-literals
          - id: check-case-conflict
          - id: check-yaml
          - id: end-of-file-fixer
          - id: check-toml
          - id: debug-statements
          - id: detect-aws-credentials
            args:
                - "--allow-missing-credentials"
          - id: detect-private-key
          - id: double-quote-string-fixer
          - id: trailing-whitespace
          - id: fix-byte-order-marker
          - id: sort-simple-yaml

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: "f12edd9c7be1c20cfa42420fd0e6df71e42b51ea" # frozen: v4.0.0-alpha.8
      hooks:
          - id: prettier

    - repo: https://github.com/codespell-project/codespell
      rev: "193cd7d27cd571f79358af09a8fb8997e54f8fff" # frozen: v2.3.0
      hooks:
          - id: codespell
            additional_dependencies:
                - tomli

    - repo: https://github.com/python-poetry/poetry
      rev: "c85477da8a610a87133299f996f8d8a593aa7bff" # frozen: 1.8.0
      hooks:
          - id: poetry-check
            name: "Poetry Check"
            args:
                - "--lock"
          - id: poetry-lock
            name: "Poetry Lock"
            args:
                - "--no-update"
          - id: poetry-install
            name: "Poetry Install"
            args:
                - "--sync"
                - "--no-root"
